name: Build

on:
  push:
    branches: [ windows-version ]
  pull_request:
    branches: [ windows-version ]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build TypeScript
      run: npm run build
      
    - name: Build Windows executable
      run: npm run dist:win
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TypeMate-Windows
        path: dist/*.exe
        compression-level: 0